meta:
  engine: 4.1.0
units:
  kx: u
  ky: u
  px: kx + 2
  py: ky + 2
  
  w: 18
  h: 17

  $default_width: u
  $default_height: u

  starting_x: 130
  starting_y: -150

  # Default M2 Screws
  screwSize: 1
  standoffSize: 2.5

points:
  zones:
    matrix:
      anchor:
        shift: [starting_x, starting_y]
        rotate: 8
      columns:
        
        outer-pinky:
          key:
            column_net: P2
          rows.r0.skip: true
        pinky:
          rows.r0.skip: true
          key:
            stagger: 0
            splay: 0
            column_net: P3
        ring:
          key:
            stagger: 10
            splay: -4
            column_net: P4
            adjust:
              shift: [0.7,0]
        middle:
          key:
            stagger: 7
            splay: -4
            column_net: P5
            adjust:
              shift: [1.7,0]
        index:
          rows.r0.skip: true
          key:
            stagger: -7
            column_net: P6
            adjust:
              shift: [1.7,0]
        inner:
          rows.r0.skip: true
          key:
            column_net: P7
            adjust:
              shift: [1.7,0]

      rows:
        r1:
          row_net: P9
        r2:
          row_net: P10
        r3:
          row_net: P14
    thumbfan:
      anchor:
        - ref: matrix_index_r1
          shift: [0.5kx, -1.04ky]
      columns:
        1:
          key:
            column_net: P5
        2:
          key:
            column_net: P6
            adjust:
              shift: [3,  -4]
              rotate: -20
        3:
          key:
            column_net: P7
            adjust:
              shift: [3,  -15]
              rotate: -40
      rows:
        r1:
          row_net: P16

    thumbfan2:
      anchor:
        - ref: matrix_middle_r1
          shift: [-0.5kx, -1.36ky]

      columns:
        1:
          key:
            column_net: P4
            adjust:
              rotate: 7
              shift: [16.5, -2.2]


          
      rows:
        r1:
          row_net: P16

outlines:
  keys:
    - what: rectangle
      where: true
      size: [17.5, 16.5]

      fillet: 1
  _outline:
    - what: polygon
      operation: stack
      fillet: 1
      points:
        - ref: matrix_outer-pinky_r3
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_r3
          shift: [-0.5px, 0py]
        - ref: matrix_ring_r3
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_r3
          shift: [-0.5px, 0.15py]
        - ref: matrix_middle_r3
          shift: [-0.5px, 0.5py]
        - ref: matrix_index_r3
          shift: [-0.4px, 0.85py]
        - ref: matrix_inner_r3
          shift: [-1.3px, 0.5py]
        - ref: matrix_inner_r3
          shift: [2.1px, 0.5py]
        - ref: matrix_inner_r3
          shift: [2.1px, -3.5py]
        - ref: thumbfan_3_r1
          shift: [0.5px, -0.5py]
        - ref: thumbfan_3_r1
          shift: [-0.5px, -0.5py]
        - ref: thumbfan_2_r1
          shift: [-0.5px, -0.5py]
        - ref: thumbfan_1_r1
          shift: [-0.5px, -0.5py]
        - ref: thumbfan2_1_r1
          shift: [-0.5px, -0.5py]
        - ref: thumbfan2_1_r1
          shift: [-0.9px, -0py]

        - ref: matrix_ring_r1
          shift: [-0.365px, -1py]
        - ref: matrix_outer-pinky_r1
          shift: [-0.5px, -0.5py]
  
  combo:
    - name: _outline
    - operation: stack
      name: keys

  switch_plate_keys:
    - what: rectangle
      where: true
      size: [kx-5.2,ky-5.2] # this makes it 14mm

  xlBoard:
    - name: _outline
      expand: 2

  switch_plate:
    - name: xlBoard
    - operation: subtract
      name: switch_plate_keys

  wall_outline:
    - name: xlBoard
    - operation: subtract
      name: _outline
pcbs:
  splake-ish:
    template: kicad8
    outlines:
      main:
        outline: _outline
    footprints:

      choc_hotswap:
        what: chocv1v2b0b
        where: true
        params:
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

          include_stabilizer_pad: false

          reversible: true
        adjust:
          rotate: 180
      
      ks27_hotswap:
        what: ceoloide/switch_gateron_ks27_ks33
        where: true
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          solder: false
          reversible: true
        adjust:
          rotate: 180

      via:
        what: via
        where: true
        params:
          net: "{{colrow}}"
        adjust:
          shift: [-0.38kx, 0.265ky]
      
      via2:
        what: via
        where: true
        params:
          net: "{{column_net}}"
        adjust:
          shift: [0.38kx, 0.265ky]


      diode:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -9]
          rotate: 180
        
      RGB1:
        what: ceoloide/led_sk6812mini-e
        where: matrix_pinky_r2
        params:
          P2: rgb
          P4: rgb
          reversible: true
        adjust:
          shift: [9, 10]

      
      RGB2:
        what: ceoloide/led_sk6812mini-e
        where: matrix_pinky_r1
        params:
          P2: rgb
          P4: rgb
          reversible: true
        adjust:
          shift: [25, -5]
      
      RGB3:
        what: ceoloide/led_sk6812mini-e
        where: matrix_inner_r3
        params:
          P2: rgb
          P4: rgb
          reversible: true
        adjust:
          shift: [13, 0]
      
      RGB4:
        what: ceoloide/led_sk6812mini-e
        where: matrix_inner_r1
        params:
          P2: rgb
          P4: rgb
          reversible: true
        adjust:
          shift: [25, -10]


      nicenano:
        what: ceoloide/mcu_nice_nano
        where:
          ref: matrix_inner_r3
          shift: [1.5kx, -0.35ky]
        params:
          reverse_mount: true
          reversible: true

      reset_switch:
        what: ceoloide/reset_switch_smd_side
        where: matrix_inner_r3
        params:
          from: RST
          to: GND
          reversible: true
        adjust:
          shift: [2.2kx, -0ky]
          rotate: -90
        
      ucbc:
        what: usbc
        where: matrix_inner_r3
        adjust:
          shift: [2.2kx, -1.5ky]
          rotate: 90


      screwhole1:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [matrix_pinky_r3]
          shift: [-0.5kx, -0.5ky]
      
      screwhole2:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [matrix_pinky_r2]
          shift: [-0.5kx, -0.5ky]

      screwhole3:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [matrix_middle_r2]
          shift: [-0.5kx, 0.5ky]

      screwhole4:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [matrix_middle_r1]
          shift: [0kx, -0.8ky]
      
      screwhole5:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [matrix_inner_r1]
          shift: [0.7kx, 0.8ky]

      screwhole6:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [thumbfan_2_r1]
          shift: [0.6kx, 0ky]
      


cases:
  _wall:
    - name: wall_outline
      extrude: 7
  plate_tester:
    - what: case
      name: _wall
    - name: switch_plate
      shift: [0,0,5]
      extrude: 2

  # case:
  #   - what: case
  #     name: _wall
  #     operation: add
  #   - name: xlBoard
  #     operation: add